"""Built-in per-route widget HTML generated by Python (no npm/React build)."""

from __future__ import annotations

from typing import Any, Callable, Dict, Optional

from nitrostack.widgets.host_bridge import wrap_widget_page
from nitrostack.widgets.views import missing_body, render_body


def _generic_render_js() -> str:
    return """
window.__nitroWidgetRender = function(data) {
  const root = document.getElementById("root");
  const meta = document.getElementById("meta");
  if (!root) return;
  if (!data) {
    if (meta) meta.textContent = "Waiting for tool result (host injects tool output).";
    return;
  }
  if (meta) meta.textContent = "Tool output";
  root.innerHTML = "";
  const pre = document.createElement("pre");
  pre.textContent = JSON.stringify(data, null, 2);
  root.appendChild(pre);
};
""".strip()


_PIZZA_LIST_CSS = """
    :root { --ns-accent: #ea580c; --ns-accent-soft: #ffedd5; }
    .shop { min-width: 260px; max-width: 260px; scroll-snap-align: start; flex-shrink: 0; }
    .img { width: 100%; height: 120px; object-fit: cover; border-radius: 10px; margin-bottom: 8px; background: var(--ns-accent-soft); }
    .row { display: flex; justify-content: space-between; gap: 8px; align-items: baseline; }
    .name { font-weight: 700; }
    .addr { color: var(--ns-muted); font-size: 0.85rem; margin-top: 4px; }
"""

_PIZZA_MAP_CSS = """
    :root { --ns-accent: #ea580c; }
    html, body { width: 100%; height: 560px; }
    body { position: relative; min-height: 560px; background: #e5e7eb; }
    .meta { position: absolute; top: 12px; left: 12px; z-index: 3; margin: 0;
      background: color-mix(in srgb, var(--ns-surface) 92%, transparent); border-radius: 8px; padding: 6px 10px;
      box-shadow: var(--ns-shadow); }
    .map { position: absolute; inset: 0; width: 100%; height: 560px; min-height: 560px; }
    .map-live { position: absolute; inset: 0; }
    .static-map { position: absolute; inset: 0; z-index: 1; width: 100%; height: 560px;
      object-fit: cover; transition: opacity .4s ease; }
    .static-map.is-ready { opacity: 0; pointer-events: none; }
    .mapboxgl-map { width: 100%; height: 100%; }
    .cards { position: absolute; left: 16px; right: 16px; bottom: 8px; z-index: 3; }
    .map-card { min-width: 220px; max-width: 220px; flex-shrink: 0; scroll-snap-align: start; }
    .map-card .name { font-weight: 700; }
    .map-card .muted { margin-top: 4px; }
    .map-card .rating { margin-top: 4px; }
"""

_PIZZA_SHOP_CSS = """
    :root { --ns-accent: #e11d48; --ns-accent-soft: #ffe4e6; }
    .card { background: var(--ns-surface); border-radius: var(--ns-radius); padding: 16px; border: 1px solid var(--ns-border); }
    .hero { width: 100%; max-height: 180px; object-fit: cover; border-radius: 10px; margin-bottom: 12px; }
    .chips { margin-top: 10px; }
    .chip { margin: 0 4px 4px 0; }
"""

_CALC_CSS = """
    :root { --ns-accent: #15803d; }
    .card { background: var(--ns-surface); border: 1px solid var(--ns-border); border-radius: var(--ns-radius); padding: 20px; text-align: center; }
    .expr { font-size: 0.95rem; color: var(--ns-muted); margin-bottom: 8px; }
    .result { font-size: 2rem; font-weight: 800; color: var(--ns-accent); }
"""

_CARD_CSS = """
    .card { background: var(--ns-surface); border-radius: var(--ns-radius); padding: 20px; box-shadow: var(--ns-shadow); max-width: 320px; border: 1px solid var(--ns-border); }
    .card h2 { margin: 0 0 8px; font-size: 1.25rem; }
    .price { font-size: 1.5rem; }
    .desc { color: var(--ns-muted); margin-top: 8px; }
"""

_TABLE_CSS = """
    table { border-collapse: collapse; width: 100%; max-width: 480px; background: var(--ns-surface); border-radius: 10px; overflow: hidden; }
    th, td { border: 1px solid var(--ns-border); padding: 8px 12px; text-align: left; }
    th { background: var(--ns-accent-soft); }
"""

_CHART_CSS = """
    .chart { display: flex; align-items: flex-end; gap: 8px; height: 160px; }
    .bar-wrap { flex: 1; display: flex; flex-direction: column; align-items: center; }
    .bar { width: 100%; background: var(--ns-accent, #3b82f6); border-radius: 4px 4px 0 0; min-height: 4px; }
    .label { font-size: 12px; margin-top: 4px; color: var(--ns-muted); }
"""

_FLIGHT_CSS = """
    :root { --ns-accent: #0369a1; --ns-accent-soft: #e0f2fe; }
    .offer, .card, #list .row { background: var(--ns-surface); border: 1px solid var(--ns-border); border-radius: var(--ns-radius); padding: 12px; margin-bottom: 10px; }
    .row { display: flex; gap: 12px; align-items: center; }
    .id { font-size: 0.8rem; color: var(--ns-muted); }
    .code { font-size: 1.1rem; font-weight: 800; min-width: 3rem; }
    .slice { margin-top: 8px; }
    .seat-row { display: flex; gap: 6px; align-items: center; margin: 4px 0; }
    .rn { width: 2rem; font-size: 0.8rem; color: var(--ns-muted); }
    .seat { display: inline-block; min-width: 2.4rem; text-align: center; padding: 4px; border-radius: 6px; font-size: 0.75rem; }
"""

_GENERIC_CSS = """
    pre { background: var(--ns-surface); border: 1px solid var(--ns-border); border-radius: 8px; padding: 12px; overflow: auto; }
"""

_MISSING_CSS = """
    :root { --ns-bg: #fef2f2; --ns-text: #7f1d1d; }
    .meta { font-size: 0.9rem; line-height: 1.5; }
"""

_PIZZA_LIST_JS = """
window.__nitroWidgetRender = function(data) {
  const list = document.getElementById("list");
  const meta = document.getElementById("meta");
  if (!list || !meta) return;
  list.innerHTML = "";
  if (!data || !Array.isArray(data.shops)) {
    meta.textContent = "Waiting for show_pizza_list result.";
    return;
  }
  const state = (window.openai && window.openai.widgetState) || {};
  const sort = state.sort || "rating";
  const shops = data.shops.slice().sort(function(a, b) {
    if (sort === "name") return String(a.name || "").localeCompare(String(b.name || ""));
    return (b.rating || 0) - (a.rating || 0);
  });
  document.querySelectorAll("#sorts [data-sort]").forEach(function(btn) {
    btn.classList.toggle("is-on", btn.getAttribute("data-sort") === sort);
  });
  const total = data.totalShops ?? data.shops.length;
  meta.textContent = total + " shop" + (total === 1 ? "" : "s");
  if (!shops.length) {
    list.innerHTML = '<div class="empty">No shops match these filters.</div>';
    return;
  }
  shops.forEach(function(shop) {
    const el = document.createElement("article");
    el.className = "shop ns-card";
    el.setAttribute("data-call-tool", "show_pizza_shop");
    el.setAttribute("data-args", JSON.stringify({ shopId: shop.id || "" }));
    el.setAttribute("role", "button");
    el.tabIndex = 0;
    const open = shop.openNow
      ? '<span class="badge open">Open</span>'
      : '<span class="badge closed">Closed</span>';
    const price = "$".repeat(shop.priceLevel || 1);
    let img = "";
    if (shop.image) {
      img = '<img class="img" src="' + shop.image + '" alt="" />';
    }
    el.innerHTML =
      img +
      '<div class="row"><span class="name"></span><span class="rating"></span></div>' +
      '<div class="addr"></div><div>' + open + ' <span class="badge price"></span></div>';
    el.querySelector(".name").textContent = shop.name || shop.id || "Shop";
    el.querySelector(".rating").textContent = shop.rating != null ? "★ " + shop.rating : "";
    el.querySelector(".addr").textContent = shop.address || "";
    el.querySelector(".price").textContent = price;
    list.appendChild(el);
  });
};
document.addEventListener("click", function(ev) {
  const btn = ev.target.closest("#sorts [data-sort]");
  if (!btn || !window.nitrostack) return;
  const next = Object.assign({}, (window.openai && window.openai.widgetState) || {}, {
    sort: btn.getAttribute("data-sort")
  });
  window.nitrostack.setWidgetState(next);
  if (typeof window.__nitroWidgetRender === "function" && window.nitrostack.readHostData) {
    window.__nitroWidgetRender(window.nitrostack.readHostData());
  }
});
""".strip()

_MAPBOX_HEAD = """
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v3.8.0/mapbox-gl.css" />
  <script src="https://api.mapbox.com/mapbox-gl-js/v3.8.0/mapbox-gl.js"></script>
""".strip()


def _pizza_map_js() -> str:
    import json

    from nitrostack.widgets.html_util import get_mapbox_token

    token = json.dumps(get_mapbox_token())
    return f"""
window.__NITRO_MAPBOX_TOKEN = {token};
window.__nitroWidgetRender = function(data) {{
  const meta = document.getElementById("meta");
  const mapEl = document.getElementById("map-live") || document.getElementById("map");
  const cards = document.getElementById("cards");
  const staticEl = document.getElementById("static-map");
  if (!mapEl) return;
  if (!data || !Array.isArray(data.shops) || !data.shops.length) {{
    if (meta) meta.textContent = "Waiting for show_pizza_map result.";
    return;
  }}
  const shops = data.shops.filter(function(s) {{ return Array.isArray(s.coords) && s.coords.length === 2; }});
  const sig = (data.filter || "all") + "|" + shops.map(function(s) {{
    return (s.id || "") + ":" + s.coords[0] + "," + s.coords[1];
  }}).join(";");
  if (window.__nitroMapSig === sig && window.__nitroMap) return;
  if (meta) meta.textContent = (data.totalShops ?? data.shops.length) + " shops · filter: " + (data.filter || "all");
  if (cards && !cards.querySelector(".map-card")) {{
    data.shops.forEach(function(shop) {{
      const card = document.createElement("article");
      card.className = "map-card ns-card";
      card.setAttribute("data-shop-id", shop.id || "");
      card.setAttribute("data-call-tool", "show_pizza_shop");
      card.setAttribute("data-args", JSON.stringify({{ shopId: shop.id || "" }}));
      card.setAttribute("role", "button");
      card.tabIndex = 0;
      card.innerHTML = '<div class="name"></div><div class="muted"></div><div class="rating"></div>';
      card.querySelector(".name").textContent = shop.name || shop.id || "Shop";
      card.querySelector(".muted").textContent = shop.address || "";
      card.querySelector(".rating").textContent = shop.rating != null ? "★ " + shop.rating : "";
      cards.appendChild(card);
    }});
  }}
  function revealLive() {{
    if (staticEl) staticEl.classList.add("is-ready");
  }}
  function mountMap(attempt) {{
    if (window.__nitroMapSig === sig && window.__nitroMap) return;
    if (!window.__NITRO_MAPBOX_TOKEN) {{
      return;
    }}
    if (typeof mapboxgl === "undefined") {{
      if ((attempt || 0) < 80) {{
        setTimeout(function() {{ mountMap((attempt || 0) + 1); }}, 50);
      }}
      return;
    }}
    window.__nitroMapSig = sig;
    if (window.__nitroMap) {{
      window.__nitroMap.remove();
      window.__nitroMap = null;
    }}
    mapboxgl.accessToken = window.__NITRO_MAPBOX_TOKEN;
    const first = (shops[0] && shops[0].coords) || [-122.4194, 37.7749];
    const map = new mapboxgl.Map({{
      container: mapEl,
      style: "mapbox://styles/mapbox/streets-v12",
      center: first,
      zoom: 12,
      cooperativeGestures: false,
      fadeDuration: 0
    }});
    map.addControl(new mapboxgl.NavigationControl({{ showCompass: false }}), "top-right");
    map.addControl(new mapboxgl.FullscreenControl(), "top-right");
    shops.forEach(function(shop) {{
      const el = document.createElement("div");
      el.style.backgroundImage = "url(https://docs.mapbox.com/mapbox-gl-js/assets/custom_marker.png)";
      el.style.width = "30px";
      el.style.height = "40px";
      el.style.backgroundSize = "100%";
      el.style.cursor = "pointer";
      el.title = shop.name || shop.id || "";
      el.addEventListener("click", function() {{
        if (window.nitrostack) window.nitrostack.callTool("show_pizza_shop", {{ shopId: shop.id || "" }});
      }});
      new mapboxgl.Marker(el).setLngLat(shop.coords).addTo(map);
    }});
    if (shops.length > 1) {{
      const bounds = new mapboxgl.LngLatBounds();
      shops.forEach(function(s) {{ bounds.extend(s.coords); }});
      map.fitBounds(bounds, {{ padding: 60, maxZoom: 14, duration: 0 }});
    }}
    map.once("idle", function() {{
      try {{ map.resize(); }} catch (e) {{}}
      revealLive();
    }});
    window.__nitroMap = map;
  }}
  mountMap(0);
}};
""".strip()

_PIZZA_SHOP_JS = """
window.__nitroWidgetRender = function(data) {
  const shop = data && (data.shop || data);
  const hero = document.getElementById("hero");
  if (!shop || !shop.name) {
    const desc = document.getElementById("desc");
    if (desc) desc.textContent = "Waiting for show_pizza_shop result.";
    return;
  }
  if (shop.image && hero) {
    hero.src = shop.image;
    hero.style.display = "block";
  } else if (hero) {
    hero.style.display = "none";
  }
  document.getElementById("name").textContent = shop.name;
  document.getElementById("rating").textContent =
    shop.rating != null ? "★ " + shop.rating + " (" + (shop.reviews || 0) + " reviews)" : "";
  document.getElementById("desc").textContent = shop.description || "";
  document.getElementById("addr").textContent = shop.address || "";
  const hours = shop.hours ? (shop.hours.open + " – " + shop.hours.close) : "";
  document.getElementById("hours").textContent = hours ? "Hours: " + hours : "";
  document.getElementById("phone").textContent = shop.phone || "";
  const chips = document.getElementById("chips");
  chips.innerHTML = "";
  (shop.specialties || []).forEach(function(item) {
    const chip = document.createElement("span");
    chip.className = "chip";
    chip.textContent = item;
    chips.appendChild(chip);
  });
  const actions = document.getElementById("actions");
  if (actions) {
    actions.innerHTML = "";
    function addLink(label, url, primary) {
      if (!url) return;
      const a = document.createElement("a");
      a.className = primary ? "ns-btn ns-btn-primary" : "ns-btn";
      a.setAttribute("data-open-link", url);
      a.href = url;
      a.textContent = label;
      actions.appendChild(a);
    }
    let maps = "";
    if (Array.isArray(shop.coords) && shop.coords.length === 2) {
      maps = "https://www.google.com/maps/search/?api=1&query=" + shop.coords[1] + "," + shop.coords[0];
    } else if (shop.address) {
      maps = "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(shop.address);
    }
    addLink("Maps", maps, false);
    if (shop.phone) {
      const tel = String(shop.phone).replace(/[^0-9+]/g, "");
      if (tel) addLink("Call", "tel:" + tel, false);
    }
    addLink("Website", shop.website || "", true);
  }
};
""".strip()

_CALC_JS = """
window.__nitroWidgetRender = function(data) {
  if (!data) return;
  const expr = document.getElementById("expr");
  const result = document.getElementById("result");
  if (data.expression) expr.textContent = data.expression;
  if (data.result != null) result.textContent = String(data.result);
  else if (data.value != null) result.textContent = String(data.value);
};
""".strip()

_CARD_JS = """
window.__nitroWidgetRender = function(data) {
  if (!data) return;
  const name = document.getElementById("name");
  const price = document.getElementById("price");
  const desc = document.getElementById("desc");
  if (name) name.textContent = data.name || "—";
  if (price) price.textContent = data.price != null ? "$" + Number(data.price).toFixed(2) : "—";
  if (desc) desc.textContent = data.description || "";
};
""".strip()

_TABLE_JS = """
window.__nitroWidgetRender = function(data) {
  if (!data || !Array.isArray(data.rows)) return;
  const cols = data.columns || Object.keys(data.rows[0] || {});
  const header = document.getElementById("header");
  const body = document.getElementById("body");
  if (!header || !body) return;
  header.innerHTML = "";
  body.innerHTML = "";
  cols.forEach(function(c) {
    const th = document.createElement("th");
    th.textContent = c;
    header.appendChild(th);
  });
  data.rows.forEach(function(row) {
    const tr = document.createElement("tr");
    cols.forEach(function(c) {
      const td = document.createElement("td");
      td.textContent = row[c] ?? "";
      tr.appendChild(td);
    });
    body.appendChild(tr);
  });
};
""".strip()

_CHART_JS = """
window.__nitroWidgetRender = function(data) {
  if (!data) return;
  const title = document.getElementById("title");
  const chart = document.getElementById("chart");
  if (title) title.textContent = data.title || "Chart";
  if (!chart) return;
  chart.innerHTML = "";
  const items = data.items || [];
  const max = Math.max.apply(null, items.map(function(i) { return i.value || 0; }).concat([1]));
  items.forEach(function(item) {
    const wrap = document.createElement("div");
    wrap.className = "bar-wrap";
    const bar = document.createElement("div");
    bar.className = "bar";
    bar.style.height = (((item.value || 0) / max) * 140) + "px";
    const label = document.createElement("div");
    label.className = "label";
    label.textContent = item.label || "";
    wrap.appendChild(bar);
    wrap.appendChild(label);
    chart.appendChild(wrap);
  });
};
""".strip()


_FLIGHT_SEARCH_JS = """
window.__nitroWidgetRender = function(data) {
  const list = document.getElementById("list");
  const meta = document.getElementById("meta");
  if (!list) return;
  const offers = (data && (data.offers || data.results)) || [];
  const params = (data && data.searchParams) || {};
  const total = (data && data.totalOffers != null) ? data.totalOffers : offers.length;
  if (meta) {
    meta.textContent = (params.origin && params.destination)
      ? (params.origin + " → " + params.destination + " · " + total + " offer" + (total === 1 ? "" : "s"))
      : (total + " offer" + (total === 1 ? "" : "s"));
  }
  list.innerHTML = "";
  if (!offers.length) {
    list.innerHTML = '<div class="empty">No flight offers.</div>';
    return;
  }
  function code(p) {
    if (!p) return "";
    if (typeof p === "string") return p;
    return p.iata_code || p.iataCode || p.code || "";
  }
  function legs(offer) {
    if (offer.slices && offer.slices.length) return offer.slices;
    const out = [];
    if (offer.outbound) out.push(offer.outbound);
    if (offer.return) out.push(offer.return);
    return out;
  }
  offers.forEach(function(offer) {
    const el = document.createElement("article");
    el.className = "offer ns-card";
    el.setAttribute("data-call-tool", "get_flight_details");
    el.setAttribute("data-args", JSON.stringify({ offerId: offer.id || "" }));
    el.setAttribute("role", "button");
    el.tabIndex = 0;
    const amount = offer.total_amount || offer.totalAmount || "";
    const currency = offer.total_currency || offer.totalCurrency || "";
    el.innerHTML = '<div class="row"><span class="price"></span><span class="id"></span></div>';
    el.querySelector(".price").textContent = amount + (currency ? " " + currency : "");
    el.querySelector(".id").textContent = offer.id || "";
    legs(offer).forEach(function(sl) {
      const s = document.createElement("div");
      s.className = "slice";
      s.textContent = code(sl.origin) + " → " + code(sl.destination) + " · " + (sl.duration || "");
      el.appendChild(s);
    });
    list.appendChild(el);
  });
};
""".strip()

_AIRPORT_JS = """
window.__nitroWidgetRender = function(data) {
  const list = document.getElementById("list");
  const meta = document.getElementById("meta");
  if (!list) return;
  const results = (data && (data.results || data.airports || data.places)) || [];
  if (meta) meta.textContent = "Query: " + ((data && data.query) || "") + " · " + results.length + " result(s)";
  list.innerHTML = "";
  if (!results.length) {
    list.innerHTML = '<div class="empty">No airports found.</div>';
    return;
  }
  results.forEach(function(item) {
    const el = document.createElement("div");
    el.className = "row";
    el.innerHTML = '<span class="code"></span><div><div class="name"></div><div class="muted"></div></div>';
    el.querySelector(".code").textContent = item.iata_code || item.iataCode || "";
    el.querySelector(".name").textContent = item.name || "";
    el.querySelector(".muted").textContent = (item.city_name || item.cityName || item.city || "") + " · " + (item.type || "airport");
    list.appendChild(el);
  });
};
""".strip()


def _place_code_js() -> str:
    return """
  function code(p) {
    if (!p) return "";
    if (typeof p === "string") return p;
    return p.iata_code || p.iataCode || p.code || "";
  }
  function money(amount, currency) {
    if (amount == null || amount === "") return "";
    return String(amount) + (currency ? " " + currency : "");
  }
  function sliceHtml(sl) {
    const origin = code(sl.origin);
    const dest = code(sl.destination);
    const wrap = document.createElement("div");
    wrap.className = "slice";
    const title = document.createElement("strong");
    title.textContent = origin + " → " + dest;
    const times = document.createElement("div");
    times.className = "muted";
    times.textContent = (sl.departing_at || sl.departingAt || sl.departureTime || "") +
      " – " + (sl.arriving_at || sl.arrivingAt || sl.arrivalTime || "") +
      " · " + (sl.duration || "");
    wrap.appendChild(title);
    wrap.appendChild(times);
    return wrap;
  }
""".strip()


_FLIGHT_DETAILS_JS = f"""
window.__nitroWidgetRender = function(data) {{
  const meta = document.getElementById("meta");
  const root = document.getElementById("root");
  if (!root) return;
  if (!data) {{
    if (meta) meta.textContent = "Waiting for get_flight_details result.";
    return;
  }}
{_place_code_js()}
  const amount = data.total_amount || data.totalAmount || "";
  const currency = data.total_currency || data.totalCurrency || "";
  if (meta) meta.textContent = "Offer " + (data.id || "") + " · " + money(amount, currency);
  root.innerHTML = "";
  (data.slices || []).forEach(function(sl) {{ root.appendChild(sliceHtml(sl)); }});
  if (data.id) {{
    const actions = document.createElement("div");
    actions.className = "ns-actions";
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "ns-btn ns-btn-primary";
    btn.setAttribute("data-call-tool", "get_seat_map");
    btn.setAttribute("data-args", JSON.stringify({{ offerId: data.id }}));
    btn.textContent = "Seat map";
    actions.appendChild(btn);
    root.appendChild(actions);
  }}
}};
""".strip()

_ORDER_SUMMARY_JS = f"""
window.__nitroWidgetRender = function(data) {{
  const root = document.getElementById("root");
  const card = document.querySelector(".card");
  if (!data) return;
{_place_code_js()}
  const status = data.status || "held";
  const ref = data.booking_reference || data.bookingReference || "";
  const orderId = data.id || data.orderId || "";
  const amount = data.total_amount || data.totalAmount || "";
  const currency = data.total_currency || data.totalCurrency || "";
  const host = card || root;
  if (!host) return;
  host.innerHTML = "";
  const h1 = document.createElement("h1");
  h1.textContent = "Order " + status;
  const meta = document.createElement("div");
  meta.className = "meta";
  meta.textContent = "Ref " + ref + " · " + orderId;
  const price = document.createElement("div");
  price.className = "price";
  price.textContent = money(amount, currency);
  host.appendChild(h1);
  host.appendChild(meta);
  host.appendChild(price);
  const paxTitle = document.createElement("h2");
  paxTitle.textContent = "Passengers";
  host.appendChild(paxTitle);
  const passengers = data.passengers || [];
  if (!passengers.length) {{
    const empty = document.createElement("div");
    empty.className = "muted";
    empty.textContent = "None listed";
    host.appendChild(empty);
  }}
  passengers.forEach(function(p) {{
    const line = document.createElement("div");
    line.className = "muted";
    line.textContent = p.name || [p.given_name || p.givenName, p.family_name || p.familyName].filter(Boolean).join(" ") || p.id || "";
    host.appendChild(line);
  }});
  const itin = document.createElement("h2");
  itin.textContent = "Itinerary";
  host.appendChild(itin);
  (data.slices || []).forEach(function(sl) {{ host.appendChild(sliceHtml(sl)); }});
  if (orderId && String(status).toLowerCase().indexOf("cancel") < 0) {{
    const actions = document.createElement("div");
    actions.className = "ns-actions";
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "ns-btn";
    btn.setAttribute("data-call-tool", "cancel_order");
    btn.setAttribute("data-args", JSON.stringify({{ orderId: orderId }}));
    btn.textContent = "Cancel order";
    actions.appendChild(btn);
    host.appendChild(actions);
  }}
}};
""".strip()

_SEAT_JS = """
window.__nitroWidgetRender = function(data) {
  const meta = document.getElementById("meta");
  const root = document.getElementById("root");
  if (!root) return;
  if (!data) {
    if (meta) meta.textContent = "Waiting for get_seat_map result.";
    return;
  }
  if (meta) meta.textContent = "Offer " + (data.offerId || data.offer_id || "");
  root.innerHTML = "";
  const cabins = data.cabins || [];
  if (!cabins.length) {
    root.innerHTML = '<div class="empty">No seat map data.</div>';
    return;
  }
  cabins.forEach(function(cabin) {
    const h2 = document.createElement("h2");
    h2.textContent = cabin.cabin_class || cabin.cabinClass || "cabin";
    root.appendChild(h2);
    (cabin.rows || []).forEach(function(row) {
      const line = document.createElement("div");
      line.className = "seat-row";
      const rn = document.createElement("span");
      rn.className = "rn";
      rn.textContent = row.row_number || row.rowNumber || "";
      line.appendChild(rn);
      let seats = row.seats || row.elements || [];
      if (!seats.length) {
        (row.sections || []).forEach(function(section) {
          seats = seats.concat(section.elements || []);
        });
      }
      seats.forEach(function(seat) {
        if (seat.type && seat.type !== "seat") return;
        const cell = document.createElement("span");
        const available = seat.available != null ? seat.available : (seat.available_services != null);
        cell.className = available ? "seat ok" : "seat no";
        cell.textContent = seat.designator || seat.id || seat.column || "";
        line.appendChild(cell);
      });
      root.appendChild(line);
    });
  });
};
""".strip()

_CANCEL_JS = """
window.__nitroWidgetRender = function(data) {
  const card = document.querySelector(".card");
  if (!card || !data) return;
  const status = data.status || "cancelled";
  const cid = data.id || data.cancellationId || "";
  const refund = data.refund_amount || data.refundAmount || "";
  const currency = data.refund_currency || data.refundCurrency || "";
  card.innerHTML = "";
  const h1 = document.createElement("h1");
  h1.textContent = "Booking cancelled";
  const meta = document.createElement("div");
  meta.className = "meta";
  meta.textContent = status + " · " + cid;
  const p = document.createElement("p");
  p.textContent = data.message || "Booking cancelled.";
  const price = document.createElement("div");
  price.className = "price";
  price.textContent = "Refund " + (refund ? (refund + (currency ? " " + currency : "")) : "n/a");
  card.appendChild(h1);
  card.appendChild(meta);
  card.appendChild(p);
  card.appendChild(price);
};
""".strip()


def _page(
    title: str,
    styles: str,
    body: str,
    render_js: str,
    data: Any | None,
    extra_head: str = "",
    flush: bool = False,
    chrome: bool = True,
) -> str:
    return wrap_widget_page(
        title=title,
        styles=styles,
        body=body,
        render_js=render_js,
        data=data,
        extra_head=extra_head,
        flush=flush,
        chrome=chrome,
    )


def build_generic_widget(route: str, data: Any | None = None) -> str:
    return _page(route, _GENERIC_CSS, render_body(route, data), _generic_render_js(), data)


def build_missing_widget(route: str, data: Any | None = None) -> str:
    return _page(
        f"Missing widget: {route}",
        _MISSING_CSS,
        missing_body(route),
        _generic_render_js(),
        data,
    )


def build_pizza_list_widget(data: Any | None = None) -> str:
    return _page("Pizza shops", _PIZZA_LIST_CSS, render_body("pizza-list", data), _PIZZA_LIST_JS, data)


def build_pizza_map_widget(data: Any | None = None) -> str:
    return _page(
        "Pizza map",
        _PIZZA_MAP_CSS,
        render_body("pizza-map", data),
        _pizza_map_js(),
        data,
        extra_head=_MAPBOX_HEAD,
        flush=True,
    )


def build_pizza_shop_widget(data: Any | None = None) -> str:
    return _page("Pizza shop", _PIZZA_SHOP_CSS, render_body("pizza-shop", data), _PIZZA_SHOP_JS, data)


def build_calculator_result_widget(data: Any | None = None) -> str:
    return _page(
        "Calculator result",
        _CALC_CSS,
        render_body("calculator-result", data),
        _CALC_JS,
        data,
    )


def build_card_widget(data: Any | None = None) -> str:
    return _page("Product Card", _CARD_CSS, render_body("card", data), _CARD_JS, data)


def build_table_widget(data: Any | None = None) -> str:
    return _page("Data Table", _TABLE_CSS, render_body("table", data), _TABLE_JS, data)


def build_chart_widget(data: Any | None = None) -> str:
    return _page("Bar Chart", _CHART_CSS, render_body("chart", data), _CHART_JS, data)


def build_flight_search_results_widget(data: Any | None = None) -> str:
    return _page(
        "Flight search",
        _FLIGHT_CSS,
        render_body("flight-search-results", data),
        _FLIGHT_SEARCH_JS,
        data,
    )


def build_flight_details_widget(data: Any | None = None) -> str:
    return _page(
        "Flight details",
        _FLIGHT_CSS,
        render_body("flight-details", data),
        _FLIGHT_DETAILS_JS,
        data,
    )


def build_airport_search_widget(data: Any | None = None) -> str:
    return _page(
        "Airport search",
        _FLIGHT_CSS,
        render_body("airport-search", data),
        _AIRPORT_JS,
        data,
    )


def build_order_summary_widget(data: Any | None = None) -> str:
    return _page(
        "Order summary",
        _FLIGHT_CSS,
        render_body("order-summary", data),
        _ORDER_SUMMARY_JS,
        data,
    )


def build_seat_selection_widget(data: Any | None = None) -> str:
    return _page(
        "Seat map",
        _FLIGHT_CSS,
        render_body("seat-selection", data),
        _SEAT_JS,
        data,
    )


def build_order_cancellation_widget(data: Any | None = None) -> str:
    return _page(
        "Cancellation",
        _FLIGHT_CSS,
        render_body("order-cancellation", data),
        _CANCEL_JS,
        data,
    )


_ROUTE_BUILDERS: Dict[str, Callable[[Any | None], str]] = {
    "pizza-list": build_pizza_list_widget,
    "pizza-map": build_pizza_map_widget,
    "pizza-shop": build_pizza_shop_widget,
    "calculator-result": build_calculator_result_widget,
    "card": build_card_widget,
    "table": build_table_widget,
    "chart": build_chart_widget,
    "flight-search-results": build_flight_search_results_widget,
    "flight-details": build_flight_details_widget,
    "airport-search": build_airport_search_widget,
    "order-summary": build_order_summary_widget,
    "seat-selection": build_seat_selection_widget,
    "order-cancellation": build_order_cancellation_widget,
}


def _route_id(route: str) -> str:
    return (route or "").strip().strip("/").removeprefix("widget/").removesuffix(".html")


def render_widget_html(route: str, data: Any | None = None) -> Optional[str]:
    """Python-rendered HTML for a known route, or None if unknown."""
    route_id = _route_id(route)
    builder = _ROUTE_BUILDERS.get(route_id)
    if builder is None:
        return None
    return builder(data)


def get_builtin_route_html(route: str) -> Optional[str]:
    """Static template (no tool data) for ``resources/read`` / scaffolding."""
    return render_widget_html(route, None)


def build_widget_html_for_route(route: str) -> str:
    """HTML for scaffolding: known route template or generic JSON viewer."""
    return get_builtin_route_html(route) or build_generic_widget(_route_id(route))
